# -*- coding: utf-8 -*-
"""Copy of capture_only.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ywnzMnINCuW6nsCUXBnCxFHtYmTebOml
"""

# Import necessary libraries
import os                        # To handle directory and file operations
import cv2                       # OpenCV library for image processing and GUI display
import time                      # To add delays and timing
import subprocess                # To run terminal commands (for rclone uploads)
from datetime import datetime    # To timestamp filenames to avoid duplicates
from picamera2 import Picamera2  # To interface with Raspberry Pi Camera Module 3

#Init background input
background_label = input("Enter background label (b1= cardboard, b2= black): ").strip()

# Configuration
if background_label == "b1":
    RAW_PATH = "/home/*name*/recycle_project/data/Cardboard/"
else:
    RAW_PATH = "/home/*name*/recycle_project/data/Black/"
CLASS_LABELS = ["plastic", "glass", "aluminum", "background"]  # classification labels
# Create folders if they don't exist
for label in CLASS_LABELS:
    os.makedirs(os.path.join(RAW_PATH, label), exist_ok=True)

cam = Picamera2()   # Create camera object
cam.start()         # Start the camera stream
time.sleep(2)       # Give the camera 2 seconds to warm up

# Set initial class and image count
index = 0                           # Start with the first class (plastic)
current_label = CLASS_LABELS[index] # Get current label
count = len(os.listdir(os.path.join(RAW_PATH, current_label)))  # Count existing images for this class
# Instructions
print("\n Fast Raw Capture Started")
print("[SPACE] Save | [N] Next class | [Q] Quit")

# Init position input
position_label = input("Enter position label (p1 (side), p2 (top&bottom)): ").strip()

# Init lighting condition
light_label = input("Enter lighting position label (e.g., l1, l2, l_top): ").strip()

# Start main capture loop
try:
    while True:

        frame = cam.capture_array()                       # Capture image as a NumPy array (RGB format)
        frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)    # Convert RGB to BGR for correct color display
        frame = cv2.rotate(frame, cv2.ROTATE_180)         # Rotate 180 degree if camera is mounted upside down
         # Add label and image count to live preview
        preview = frame.copy()  # Make a copy so the original frame will not be modified
        cv2.putText(preview, f"Label: {current_label}", (10, 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255,255), 2)
        cv2.putText(preview, f"Count: {count}", (10, 60),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.8, (255,255,255), 2)
        cv2.imshow("Fast Capture Preview", preview)  # Display the live camera feed with overlay
        # Wait for key press (1ms)
        key = cv2.waitKey(1) & 0xFF
        # If SPACE is pressed → save and upload image
        if key == ord(' '):
            filename = f"{current_label}_{background_label}_{position_label}_{light_label}_{count+1:04d}.jpg"  # Create a filename
            raw_path = os.path.join(RAW_PATH, current_label, filename)  # Full path to save locally
            cv2.imwrite(raw_path, frame)                     # Save the captured image to local storage
            print(f"Captured & uploaded: {filename}")        # Notify user and update image count
            count += 1
        # If 'N' is pressed → switch to next class
        elif key == ord('n'):
            index = (index + 1) % len(CLASS_LABELS)     # Move to next class, wrap around at end
            current_label = CLASS_LABELS[index]         # Update current label
            count = len(os.listdir(os.path.join(RAW_PATH, current_label)))  # Re-count for new class
            print(f"Switched to: {current_label}")
        # If 'Q' is pressed → exit the program
        elif key == ord('q'):
            print("Quit")
            break
finally:
    try:
        cam.stop()
    except:
        pass
    cv2.destroyAllWindows()
    print("Camera released and windows closed.")